### ISSUE TITLE
Scheduler#days method somewhat complex

### ISSUE THREAD

**Issue by tyre** [nisargshah100/charity-chain#48]
- List of days could be extracted constant; maybe DateHelper contains all date-related constants, etc?
- Method name somewhat unclear -- scheduled_days might be clearer?
- Minor quibble: line 16 you don't have to say `== true` -- if self.send(day) would do the same

**Comment by wengzilla** [comment]
Thanks Maddox. You're the man.

This was a particularly sweet fix.
